# Generated by Django 4.0.2 on 2022-03-31 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psytest',
            name='ratings_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
