# Generated by Django 4.0.2 on 2022-03-03 04:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='emotions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ANGER', 'Anger'), ('SADNESS', 'Sadness'), ('SURPRISE', 'Surprise'), ('JOY', 'Joy'), ('LOVE', 'Love'), ('FEAR', 'Fear'), ('RAGE', 'Rage'), ('EXASPERATION', 'Exasperation'), ('IRRITATION', 'Irritation'), ('ENVY', 'Envy'), ('DISGUST', 'Disgust'), ('SUFFER', 'Suffering'), ('DISSAPPOINT', 'Disappointment'), ('SHAME', 'Shame'), ('NEGLECTION', 'Neglection'), ('DESPAIR', 'Despair'), ('STUN', 'Stun'), ('CONF', 'Confusion'), ('AMAZE', 'Amazement'), ('OVERCOME', 'Overcome'), ('MOVED', 'Moved'), ('CONTENT', 'Content'), ('HAPPY', 'Happiness'), ('CHEER', 'Cheer'), ('PROUD', 'Proudness'), ('OPTIMISM', 'Optimism'), ('ENTHUSIASM', 'Enthusiasm'), ('ELATION', 'Elation'), ('ENTHRALLED', 'Enthralled'), ('AFFECTION', 'Affection'), ('LONGING', 'Longing'), ('DSR', 'Desire'), ('TENDERNESS', 'Tenderness'), ('PEACE', 'Peace'), ('SCARE', 'Scare'), ('TERROR', 'Terror'), ('INSECURE', 'Insecure'), ('NERVOUSNESS', 'Nervousness'), ('HORROR', 'Horror')], max_length=16), default=list, size=None),
        ),
    ]
