# Generated by Django 4.0.2 on 2022-04-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_record_activities_alter_record_emotions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='activities',
        ),
    ]
