# Generated by Django 4.0.2 on 2022-05-28 09:57

import apps.records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_alter_recordreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.records.models.get_image_path),
        ),
        migrations.AddField(
            model_name='record',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
