# Generated by Django 4.0.2 on 2022-04-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_alter_relationshipcode_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationshippermission',
            name='relationship',
        ),
        migrations.AddField(
            model_name='relationship',
            name='permissions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qr.relationshippermission'),
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('doctor', 'user'), name='unique-doctor-patient-relationship'),
        ),
    ]
