# Generated by Django 4.0.2 on 2022-05-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='was_validated',
            field=models.BooleanField(default=False),
        ),
    ]
