# Generated by Django 4.0.2 on 2022-03-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_created_by_roadmap_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmapgoals',
            options={'verbose_name': 'Roadmap Goals Mapping', 'verbose_name_plural': 'Roadmap Goals Mapping'},
        ),
    ]
